
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "qejymfjqkwwlppzuojwb"

# Config specific to the Deno Edge Functions implementation
[functions]
# The maximum size in bytes of the request body
body_size_limit = 10485760 # 10MiB
