// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qejymfjqkwwlppzuojwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlanltZmpxa3d3bHBwenVvandiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTE3NDksImV4cCI6MjA1NTQ4Nzc0OX0.ksMzjfkHI7qc0CMeuNml3f4Zw8RVu5lKu8Qmzs9KV2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);